### ISSUE TITLE
Missing Link for Chainsformer Spark Connector in Documentation

### ISSUE THREAD

**Issue by namanjain** [coinbase/chainsformer#9]
I was going through the Chainsformer documentation and noticed that there's a mention of the "Chainsformer Spark Connector" for structured data streaming. However, the documentation also mentions that a link to the Spark Connector is to be added later  (`LINK TO BE ADDED LATTER`).

Could you please provide the missing link for the Chainsformer Spark Connector or update the documentation with the necessary information? 

Thank you!

**Comment by leozc** [comment]
We are working on it - ETA is end of FEB

**Comment by edwinchen12** [comment]
Just added the link to readme. Closing this issue.
